stages:
  - build
  - test
  - sonarqube
  - docker-image
  - docker-container
build:
  script: "mvn clean install -DskipTests"
  stage: build
test:
  dependencies:
    - sonarqube
  script: "mvn test"
  stage: test
sonarqube:
  dependencies:
    - test
  script: "mvn verify sonar:sonar"
  stage: sonarqube
docker-image:
    dependencies:
      - sonarqube
    before_script:
      - "mvn -DskipTests install"
    script: "docker build -t molspot-docker ."
    stage: docker-image
docker-container:
    dependencies:
      - docker-image
    script: "docker run -p 8080:8080 --name molspot-docker -d molspot-docker"
    stage: docker-container